import type { Course, Semester, Task } from '@/db/types'
import { uid } from '@/db/db'
import { makePhases } from './taskTypes'
import { dateForWeekday, withTime } from './semester'

/**
 * Erzeugt aus der RecurringConfig eines Kurses alle Wochen-Aufgaben des
 * Semesters (z.B. "Übungsblatt 1..14"). Das ist die Superkraft: Kurs einmal
 * definieren → das ganze Semester an Blättern entsteht mit korrekten Deadlines.
 */
export function generateRecurringTasks(course: Course, semester: Semester): Task[] {
  const cfg = course.recurring
  if (!cfg || !cfg.enabled) return []

  const tasks: Task[] = []
  const now = new Date().toISOString()

  for (let i = 0; i < cfg.count; i++) {
    const week = cfg.startWeek + i
    if (week > semester.weeks) break

    const date = withTime(dateForWeekday(semester, week, cfg.weekday), cfg.time)
    const num = i + 1

    tasks.push({
      id: uid(),
      semesterId: semester.id,
      courseId: course.id,
      type: cfg.type,
      title: `${cfg.labelPrefix} ${num}`,
      status: 'offen',
      dueDate: date.toISOString(),
      phases: makePhases(cfg.type),
      points: cfg.maxPoints != null ? { max: cfg.maxPoints } : undefined,
      order: week,
      autoGenerated: true,
      createdAt: now,
    })
  }

  return tasks
}
