import type { Course, RecurringConfig, Semester, Task } from '@/db/types'
import { uid } from '@/db/db'
import { makePhases } from './taskTypes'
import { dateForWeekday, withTime } from './semester'

/** Erzeugt die Wochen-Aufgaben einer einzelnen Serie. */
function tasksForSeries(cfg: RecurringConfig, course: Course, semester: Semester): Task[] {
  const tasks: Task[] = []
  const now = new Date().toISOString()

  for (let i = 0; i < cfg.count; i++) {
    const week = cfg.startWeek + i
    if (week > semester.weeks) break

    const date = withTime(dateForWeekday(semester, week, cfg.weekday), cfg.time)
    tasks.push({
      id: uid(),
      semesterId: semester.id,
      courseId: course.id,
      type: cfg.type,
      title: `${cfg.labelPrefix} ${i + 1}`,
      status: 'offen',
      dueDate: date.toISOString(),
      phases: makePhases(cfg.type),
      points: cfg.maxPoints != null ? { max: cfg.maxPoints } : undefined,
      order: week,
      autoGenerated: true,
      recurringId: cfg.id,
      createdAt: now,
    })
  }
  return tasks
}

/**
 * Erzeugt aus allen Wochen-Serien eines Kurses die Aufgaben des Semesters
 * (z.B. "Übungsblatt 1..14" UND "Tutoriumsblatt 1..14"). Das ist die Superkraft:
 * Kurs einmal definieren → das ganze Semester an Blättern entsteht automatisch.
 */
export function generateRecurringTasks(course: Course, semester: Semester): Task[] {
  if (!course.recurring?.length) return []
  return course.recurring.flatMap((cfg) => tasksForSeries(cfg, course, semester))
}
