// Uni-natives Datenmodell:
// Studiengang → Semester → Kurse → Aufgaben (mit Typ-Lebenszyklus)
//
// Zwei Schichten:
//   - Operativ (Board/Stundenplan/Aufgaben) ist auf das AKTIVE Semester begrenzt
//     und "resettet" beim Semesterwechsel (= Kontextwechsel, nichts wird gelöscht).
//   - Studienakte (Noten/ECTS aus Kursen) kumuliert über alle Semester eines
//     Studiengangs und wird nie zurückgesetzt.

export type ProgramType = 'bachelor' | 'master' | 'other'

export interface Program {
  id: string
  name: string // "B.Sc. Informatik"
  type: ProgramType
  targetEcts: number // 180 (Bachelor) / 120 (Master) …
  /** Startbilanz für Quereinstieg mitten im Studium (optional). */
  priorEcts?: number // bereits erbrachte ECTS vor Tool-Nutzung
  priorGradeAvg?: number // bisheriger Schnitt
  priorGradedEcts?: number // ECTS, auf denen priorGradeAvg beruht (für korrekte Gewichtung)
  active: boolean
  order: number
  createdAt: string
}

export type TaskTypeId =
  | 'uebung'
  | 'hausarbeit'
  | 'referat'
  | 'lektuere'
  | 'tutorium'
  | 'klausur'
  | 'sonstiges'

/** Spalten des Boards. */
export type TaskStatus = 'offen' | 'dran' | 'erledigt'

/** Priorität einer Aufgabe (undefined = keine). */
export type Priority = 'hoch' | 'mittel' | 'niedrig'

/** Ein Klausurenphasen-Zeitraum (eine Uni kann zwei haben). */
export interface ExamPhase {
  id: string
  label: string // "1. Klausurenphase"
  start: string // ISO-Datum
  end: string // ISO-Datum
}

export interface Semester {
  id: string
  programId: string
  name: string // z.B. "SoSe 2026"
  /** ISO-Datum (yyyy-mm-dd) des Montags von Woche 1 (Vorlesungsbeginn). */
  startDate: string
  /** Anzahl Vorlesungswochen, z.B. 14. */
  weeks: number
  /** Klausurenphasen (0–2). */
  examPhases: ExamPhase[]
  /** Semesterende (ISO) – danach beginnt das nächste Semester. */
  endDate?: string
  active: boolean
}

/** Art eines Stundenplan-Termins. */
export type SlotKind = 'vorlesung' | 'uebung' | 'tutorium' | 'repetitorium' | 'klausur'

export interface CourseSlot {
  id: string
  kind: SlotKind
  /** 1 = Montag … 7 = Sonntag */
  weekday: number
  start: string // "10:00"
  end: string // "12:00"
  room?: string
}

/** Konfiguration für automatisch generierte Wochenblätter / Wochen-Lektüre. */
export interface RecurringConfig {
  enabled: boolean
  type: TaskTypeId // meist 'uebung' oder 'lektuere'
  labelPrefix: string // "Übungsblatt"
  /** 1 = Montag … 7 = Sonntag (Abgabetag) */
  weekday: number
  time?: string // "12:00"
  count: number // Anzahl Blätter
  startWeek: number // ab welcher Semesterwoche (1-basiert)
  maxPoints?: number // Punkte pro Blatt (optional)
}

/** Studienstatus eines Kurses – steuert, ob er in die Studienakte einfließt. */
export type CourseStatus = 'laufend' | 'bestanden' | 'nicht_bestanden'

export interface Course {
  id: string
  semesterId: string
  name: string // "Analysis II"
  short: string // "ANA2"
  color: string // Hex, z.B. "#6366f1"
  ects?: number
  grade?: number // 1.0 – 5.0
  status?: CourseStatus // default: 'laufend'
  slots: CourseSlot[]
  recurring?: RecurringConfig
}

export interface Phase {
  label: string
  done: boolean
}

export interface Task {
  id: string
  semesterId: string
  courseId?: string
  type: TaskTypeId
  title: string
  status: TaskStatus
  priority?: Priority
  /** ISO-Datum/-Zeit der Fälligkeit. */
  dueDate?: string
  notes?: string
  phases: Phase[]
  points?: { earned?: number; max?: number }
  /** Sortierung innerhalb einer Spalte. */
  order: number
  /** true, wenn automatisch aus RecurringConfig erzeugt. */
  autoGenerated?: boolean
  createdAt: string
  completedAt?: string
}
