// Uni-natives Datenmodell: Semester → Kurse → Aufgaben (mit Typ-Lebenszyklus)

export type TaskTypeId =
  | 'uebung'
  | 'hausarbeit'
  | 'referat'
  | 'lektuere'
  | 'klausur'
  | 'sonstiges'

/** Spalten des Boards. */
export type TaskStatus = 'offen' | 'dran' | 'erledigt'

export interface Semester {
  id: string
  name: string // z.B. "SoSe 2026"
  /** ISO-Datum (yyyy-mm-dd) des Montags von Woche 1. */
  startDate: string
  /** Anzahl Vorlesungswochen, z.B. 14. */
  weeks: number
  active: boolean
}

export interface CourseSlot {
  id: string
  kind: 'vorlesung' | 'tutorium'
  /** 1 = Montag … 7 = Sonntag */
  weekday: number
  start: string // "10:00"
  end: string // "12:00"
  room?: string
}

/** Konfiguration für automatisch generierte Wochenblätter / Wochen-Lektüre. */
export interface RecurringConfig {
  enabled: boolean
  type: TaskTypeId // meist 'uebung' oder 'lektuere'
  labelPrefix: string // "Übungsblatt"
  /** 1 = Montag … 7 = Sonntag (Abgabetag) */
  weekday: number
  time?: string // "12:00"
  count: number // Anzahl Blätter
  startWeek: number // ab welcher Semesterwoche (1-basiert)
  maxPoints?: number // Punkte pro Blatt (optional)
}

export interface Course {
  id: string
  semesterId: string
  name: string // "Analysis II"
  short: string // "ANA2"
  color: string // Hex, z.B. "#6366f1"
  ects?: number
  grade?: number // 1.0 – 5.0
  slots: CourseSlot[]
  recurring?: RecurringConfig
}

export interface Phase {
  label: string
  done: boolean
}

export interface Task {
  id: string
  semesterId: string
  courseId?: string
  type: TaskTypeId
  title: string
  status: TaskStatus
  /** ISO-Datum/-Zeit der Fälligkeit. */
  dueDate?: string
  notes?: string
  phases: Phase[]
  points?: { earned?: number; max?: number }
  /** Sortierung innerhalb einer Spalte. */
  order: number
  /** true, wenn automatisch aus RecurringConfig erzeugt. */
  autoGenerated?: boolean
  createdAt: string
  completedAt?: string
}
